DOC_TYPE="feature"; TITLE="qftp-client(ネイティブクライアント)"; FILENAME="feature-client.html"
ANSWERS={
"overview.name":"<p>qftp-client: REPL と one-shot サブコマンドを持つネイティブクライアント。ライブラリ <code>qftp-client-core</code> と CLI バイナリ <code>qftp-client</code> の 2 クレート。</p>",
"overview.purpose":"<p>scp / sftp と同じ感覚で使え、再開・整合性検証・圧縮・0-RTT が自動で効くクライアントを提供します。プロトタイプの機能を、Session API・一貫したサーバ信頼ポリシー・統一された終了コード規約のうえに再構成します。</p>",
"overview.target-user":"<p>対話利用者(REPL)、スクリプト利用者(one-shot、batch)、ライブラリ利用者(sync / watch / <code>qftp-server</code> の test-util と e2e)。</p>",
"overview.use-case":"<ol><li><code>qftp-client work</code> でエイリアス接続し、<code>ls</code> / <code>get -r</code> / <code>put</code> を対話実行。</li><li><code>qftp-client put ./dump.tar.gz qftp://files.example/backups/</code> をバックアップスクリプトから実行し、終了コードで判定。</li><li>CI から <code>--batch</code> で標準入力のコマンド列を実行。</li></ol>",
"scope.in-scope":"<ul><li>Session API: connect / request / get / put / close、再開判定、StalePartial 再試行、圧縮フォールバック。</li><li>サーバ信頼ポリシー: CA / システムルート / TOFU / insecure を <b>全経路で同一</b>に適用。</li><li>設定ファイル(<code>[defaults]</code> + <code>[host.*]</code>)、known_hosts、セッションチケット、履歴。</li><li>REPL(クォート対応パーサ、補完、進捗)、one-shot(put / get / mget / ls / stat / rm / mkdir / rmdir / rename / chmod / quota)。</li><li>拡張区分: <code>get -r</code> / <code>put -r</code> / <code>mget</code>(REPL と one-shot の両方)、双方向 <code>--bwlimit</code>。</li><li>同期区分: sync / watch。</li></ul>",
"scope.out-of-scope":"<ul><li><code>put-multi</code>(作らない。sync の複数ターゲット指定で代替、ADR-010)。</li><li>sync <code>--checksum</code>(作らない、ADR-010)。</li><li>リモート補完。</li><li>Windows(非 Unix は起動時エラー、ADR-011)。</li></ul>",
"scope.assumptions":"<ul><li>サーバは <code>qftp/1</code> 準拠。</li><li>転送のクライアント側状態機械は <code>qftp-core</code> が提供。</li></ul>",
"functional-requirements.main-flow":"""<ol><li>引数解析 → 設定解決(組込既定 &lt; <code>[defaults]</code> &lt; <code>[host.alias]</code> &lt; URL &lt; フラグ)。</li><li><code>Session::connect(spec, trust, options)</code>: 名前解決 → 各アドレスに順次接続(最後以外は 8 s 予算)→ チケットがあれば 0-RTT 再開 → ハンドシェイク → <b>信頼検査(CA モードならホスト名、TOFU なら pin)</b> → 検査前にアプリケーションデータを送らない → mTLS があれば identity はサーバ側で解決。</li><li>初期パスがあれば <code>Cd</code>。</li><li>REPL / one-shot / batch がコマンドを Session に発行。要求は逐次(1 本ずつ)。</li><li>終了時に <code>Quit</code> を送り、チケットを保存(insecure / TOFU では保存しない)。</li></ol>""",
"functional-requirements.inputs":"""<p><b>起動形態</b>: <code>qftp-client [FLAGS] [TARGET]</code>(REPL / <code>-e</code> / <code>--batch</code>)と <code>qftp-client [FLAGS] &lt;SUBCOMMAND&gt;</code>(one-shot)。TARGET は <code>qftp://[user@]host[:port][/path]</code> またはエイリアス。パスワード付き URL は拒否。</p><p><b>フラグ・サブコマンド・REPL コマンド</b>: 完全な一覧と構文は <a href="../40-reference/cli-reference.html#client-global">CLI リファレンス §3〜§5</a> が正本です。要点は、サーバ信頼(<code>--ca</code> / <code>-T</code> / <code>--insecure</code>)、mTLS、0-RTT、帯域制限、圧縮、<code>--json</code>、batch 制御(<code>--fail-fast</code>)の各フラグと、ls / cd / get / put / mget / mkdir / rmdir / rm / rename / chmod / stat / quota / ローカル操作 / <code>!</code> / stats / quit の REPL コマンドです。</p><p><b>設定ファイル</b>: <code>~/.qftp/config.toml</code> の <code>[defaults]</code>(compress / bwlimit / tofu / zero_rtt / パス類 / fail_fast)と <code>[host.*]</code>(endpoint と明示キー、プロトタイプ互換 + tofu / compress / bwlimit)。キー一覧と優先順位は <a href="../40-reference/config-reference.html#client">設定リファレンス §3</a> を参照。</p>""",
"functional-requirements.outputs":"""<p>結果は stdout、診断・進捗は stderr(進捗バーは TTY のみ)。<code>--json</code> は one-shot の結果を 1 行 JSON で出す。終了コードは sysexits(0 / 64 / 65 / 69 / 70 / 74 / 77)を全経路で守り、batch / <code>-e</code> は <code>--fail-fast</code> 既定で最初の失敗で止まる。出力形式・JSON スキーマ・ErrorCode と終了コードの対応表は <a href="../40-reference/cli-reference.html#output">CLI リファレンス §6</a> が正本です。</p>""",
"functional-requirements.business-rules":"""<table><tr><th>信頼モード</th><th>チェーン</th><th>ホスト名</th><th>ピン</th><th>0-RTT</th><th>チケット保存</th></tr>
<tr><td>既定 / <code>--ca</code></td><td>検証</td><td>SAN(RFC 6125 相当)、SAN なしなら CN</td><td>なし</td><td>有効</td><td>あり</td></tr>
<tr><td>TOFU</td><td>なし</td><td>なし</td><td>leaf SHA-256 を known_hosts に照合。<b>初回は対話なら y/n 確認、非対話なら拒否(<code>--tofu-accept-new</code> で自動受理)</b></td><td>無効</td><td>なし</td></tr>
<tr><td>insecure</td><td>なし</td><td>なし</td><td>なし</td><td>無効</td><td>なし</td></tr></table>
<ul><li>信頼検査に失敗した接続はアプリケーションデータを 1 バイトも送らずに閉じる。</li><li><b>get</b>: 既存ローカルの regular file があれば自動再開(<code>--force</code> で 0 から)。トレーラ不一致はローカル削除。再開時(offset &gt; 0)の不一致と <code>InvalidRange</code> は StalePartial として 0 から 1 回再試行、fresh の不一致は失敗(65)。<code>size + offset == total_size</code> を検査。</li><li><b>put</b>: <code>&lt;remote&gt;.qftp.partial</code> を Stat して再開(<code>--force</code> は Stat を省略し 0 から)、圧縮は ≥ 1024 バイトかつ非既圧縮拡張子、<code>checksum_trailer=true</code>、<code>Unsupported</code>(zstd)なら Identity で再送、<code>ChecksumMismatch|InvalidRange</code>(再開時)は 0 から 1 回再試行。Put ヘッダ送出後は待たずに本体を流し、<strong>同じストリームの応答を並行して読む</strong>。<code>Err</code> を受けたら送信を止めてストリームを reset する(ADR-009)。</li><li><b>ls / mget / get -r / sync</b> は <code>next_cursor</code> を必ず追う。</li><li>再帰 get: BFS、上限 10,000 ディレクトリ、エントリ名は安全名検査、既存ローカル名は再開判定に回す(スキップしない)。再帰 put: symlink はスキップし件数を報告。</li><li>上書き規則(one-shot / REPL 共通): <code>-n</code> &gt; <code>-f</code> &gt; (<code>-i</code> または TTY → 確認) &gt; 再開(再開できなければスキップ)。正本は CLI リファレンス §4。</li><li>再試行: <code>RateLimited</code> は <code>RetryAfter</code> 後に 1 回。5xx(<code>Internal</code> 等)は自動再試行しない(仕様の SHOULD は満たさない選択。スクリプト側で制御する)。</li><li>0-RTT: 再開ハンドシェイクのみ行い、early data にアプリケーションデータは載せない(プロトタイプ互換。サーバの許可リストは将来の最適化余地)。</li></ul>""",
"functional-requirements.exceptional-cases":"<ul><li>URL 不正 / 未知エイリアス: 64。エイリアス一覧を提示。</li><li>接続不能(全アドレス失敗): 69。</li><li>TOFU 不一致: SSH 風バナーを stderr に出し 77。known_hosts のパスは実際に使ったものを表示。</li><li>転送中の Ctrl-C: 現在のストリームを reset し、Quit を送って終了(partial はサーバ・ローカルとも残す)。</li><li>サーバの <code>RateLimited</code>: <code>RetryAfter</code> に従い 1 回再試行。</li><li>接続断(アイドル・サーバ終了): 69 で終了。REPL は再接続を提案しない(明示的に再起動)。</li></ul>",
"non-functional-requirements.performance":"<ul><li>読み取り / 受信チャンクは転送エンジンの <code>Limits</code>(256 KiB / 64 KiB)に従う。</li><li><code>--bwlimit</code> は上下双方向、トークンバケット(1 s バースト)。</li><li>進捗バーは 120 ms 更新。</li></ul>",
"non-functional-requirements.security":"<ul><li>known_hosts / チケット / 履歴は 0600。チケットは V2 形式(フィンガープリント埋め込み、24 h TTL)。</li><li>ローカルファイルは <code>O_NOFOLLOW</code> で開く。リモートから受けたエントリ名は安全名検査(<code>/</code> <code>\\\\</code> NUL <code>.</code> <code>..</code> 拒否)と端末エスケープ除去を通す。</li><li>パスワードは扱わない(URL のパスワードは拒否)。</li></ul>",
"non-functional-requirements.availability":"<p>N/A</p>",
"non-functional-requirements.observability":"<ul><li><code>-v</code> で tracing レベルを上げる。</li><li><code>stats</code>(REPL)と <code>--json</code>(one-shot)で転送統計。</li></ul>",
"impact.affected-features":"<ul><li><code>qftp-server</code> の test-util フィクスチャと e2e(Session API を使う)。</li><li>sync / watch(同期区分で Session API 上に実装)。</li></ul>",
"impact.external-systems":"<p>N/A</p>",
"impact.data-changes":"<p><code>~/.qftp/</code> 配下(config.toml、known_hosts、session-tickets/)。形式はプロトタイプ互換。</p>",
"risks.risks":"<ul><li>quiche ではハンドシェイク前に pin を検査できないため、「検査前にデータを送らない」規律に依存する。Session API の型で「未検証接続」と「検証済み接続」を分けて強制する。</li><li>Put の早期 <code>Err</code> は本体の一部を送った後に届き得る。送信済みバイトは無駄になるが正しさには影響しない。送信ループは受信側を毎ティック確認する。</li></ul>",
"risks.alternatives":"<ul><li>REPL ロジックをバイナリに残す(プロトタイプ形式): テスト不能で重複が増えるため不採用。</li><li>0-RTT で Cd / Stat を early data に載せる: 1 往復の節約になるが、再送・拒否処理が増える。将来の最適化候補。</li></ul>",
"references.docs":"<ul><li><a href=\"architecture-qftp.html\">アーキテクチャ設計書</a></li><li><a href=\"../40-reference/cli-reference.html\">CLI リファレンス</a>、<a href=\"../40-reference/config-reference.html\">設定リファレンス</a>、<a href=\"../40-reference/file-formats.html\">ファイル形式リファレンス</a>(known_hosts、チケット)</li><li><a href=\"feature-transfer-engine.html\">転送エンジン</a></li><li><a href=\"sequence-get-transfer.html\">Get シーケンス</a>、<a href=\"sequence-put-transfer.html\">Put シーケンス</a></li><li><a href=\"../10-protocol/error-codes.md\">error-codes.md</a>(再試行規則)</li></ul>",
"references.artifacts":"<p>N/A</p>",
}
