DOC_TYPE="feature"; TITLE="qftp-web-bridge(WebTransport ブリッジ)"; FILENAME="feature-web-bridge.html"
ANSWERS={
"overview.name":"<p>qftp-web-bridge: ブラウザから qftp を利用するための WebTransport(HTTP/3)終端。Web 区分。</p>",
"overview.purpose":"<p>クライアント証明書を出せないブラウザに、ベアラトークン認証で同じストレージを公開する。転送エンジンを共有し、ネイティブとの機能差(再開・圧縮・Cd)をなくす。</p>",
"overview.target-user":"<p>ブラウザ利用者(Chrome / Edge / Firefox。Safari は WebTransport 非対応)。</p>",
"overview.use-case":"<ol><li>社内ポータルからのファイル取得。</li><li>外部協力者へのアップロード窓口(トークン + origin 制限)。</li></ol>",
"scope.in-scope":"<ul><li>WebTransport セッション受付、origin 検査、トークン認証(ハッシュ照合、失敗レート制限)。</li><li>1 双方向ストリーム = 1 Request、セッション単位の cwd 保持。</li><li>転送エンジンの tokio ホスト実装(再開・圧縮対応)。</li><li>SPA の静的配信(開発用、hyper)。</li></ul>",
"scope.out-of-scope":"<ul><li>mTLS。</li><li>ネイティブサーバへのプロキシ(直接ストレージを扱う)。</li><li>サーバとブリッジ間のクォータ共有(別プロセスのため独立。運用設計書に制約を記載)。</li></ul>",
"scope.assumptions":"<p>トランスポートは wtransport(quinn + tokio)で確定(ADR-006)。quiche の h3 は拡張 CONNECT までしか実装しておらず、WebTransport のストリーム振り分けを外側から足せないことを調査で確認済み。</p>",
"functional-requirements.main-flow":"<ol><li>CONNECT 受理 → origin 検査 → <code>:path</code> の <code>token=</code> をハッシュ照合 → ユーザ確定(10 s 以内)。</li><li>セッション状態(user、cwd)を作成。</li><li>双方向ストリームごとに Request をデコード → ACL → メタデータ操作(<code>spawn_blocking</code>)または転送エンジン(tokio ホスト)。</li></ol>",
"functional-requirements.inputs":"<p>設定: <code>cert</code> / <code>key</code>、<code>bind</code>(UDP 4433)、<code>root</code>、<code>users</code>、<code>tokens</code>、<code>http_bind</code>(開発用)、<code>allowed_origins</code>、<code>limits.max_sessions</code>(256)、<code>limits.max_streams_per_session</code>(64)、<code>limits.auth_failures_per_ip</code>。</p>",
"functional-requirements.outputs":"<p>ワイヤ応答(qftp/1 と同一)、ログ、メトリクス(サーバと同名 + <code>qftp_web_sessions_open</code>、<code>qftp_web_auth_failures_total</code>)。</p>",
"functional-requirements.business-rules":"<ul><li>origin ポリシー: 未設定 → 非ブラウザ許可、ブラウザはトークン認証時のみ、anonymous では拒否。<code>*</code> → 全許可。リスト → 正規化完全一致。</li><li>トークンは SHA-256 で保存(ADR-012)、定数時間照合、per-IP の失敗レート制限。</li><li>anonymous は read-only。</li><li>SPA 配信は開発用。本番は静的ホスティングまたはリバースプロキシ。</li></ul>",
"functional-requirements.exceptional-cases":"<ul><li>origin 不許可 / トークン不正: CONNECT を 403 で拒否。</li><li>認証タイムアウト: セッション close。</li><li>セッション・ストリーム上限: 受付拒否。</li></ul>",
"non-functional-requirements.performance":"",
"non-functional-requirements.security":"<p><a href=\"../10-protocol/security-model.md\">security-model.md</a> の「Browser bridge」節。加えて: <code>/config.json</code> の証明書ハッシュは HTTPS 経由でのみ信頼、pin フォールバックは証明書エラー時のみ。</p>",
"non-functional-requirements.availability":"",
"non-functional-requirements.observability":"<p>サーバと同じログ構造(セッション ID を追加)。</p>",
"impact.affected-features":"<ul><li>転送エンジン(tokio ホスト)。</li><li>qftp-admin(tokens.toml)。</li></ul>",
"impact.external-systems":"<p>リバースプロキシ(nginx 等、静的配信のみ。WebTransport は中継されない)。</p>",
"impact.data-changes":"<p>tokens.toml(ハッシュ形式)。</p>",
"risks.risks":"<ul><li>quinn 系スタックがワークスペースに残る(MSRV 差、依存重複)。ブリッジをビルドしない構成(feature / 別ワークスペース)を用意して、ネイティブだけの利用者に負担を掛けない。</li><li>ブラウザ側の codec / BLAKE3 / zstd を JS で持つか WASM で共有するかで保守性が大きく変わる。</li></ul>",
"risks.alternatives":"<ul><li>ブリッジを廃止し、ブラウザ利用は WebDAV 等の別プロダクトに委ねる。</li><li><code>qftp-wire</code> + blake3 + zstd を WASM 化して SPA と共有(推奨、Web 区分で評価)。</li></ul>",
"references.docs":"<ul><li><a href=\"feature-transfer-engine.html\">転送エンジン</a>、<a href=\"../40-reference/engine-api.html\">転送エンジン API 仕様</a></li><li><a href=\"../40-reference/file-formats.html#tokens\">tokens.toml の形式</a></li><li>画面設計書は Web 区分の着手時にテンプレートから作成する</li></ul>",
"references.artifacts":"<p>N/A</p>",
}
