[package]
name = "qftp-server"
description = "QUIC File Transfer Protocol -- server."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"

[dependencies]
qftp-common = { path = "../qftp-common" }
quiche = "0.22"
rcgen = "0.13"
mio = { version = "1", features = ["net", "os-poll"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
ring = "0.17"
signal-hook = "0.3"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
hmac = "0.12"
sha2 = "0.10"
x509-parser = "0.16"
blake3 = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
