[package]
name = "qftp-client"
description = "QUIC File Transfer Protocol -- client."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"

[dependencies]
qftp-common = { path = "../qftp-common" }
quiche = "0.22"
mio = { version = "1", features = ["net", "os-poll"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
rustyline = "15"
ring = "0.17"
blake3 = "1"
indicatif = "0.18"
glob = "0.3"
url = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3"

